Support passing in true/false string in boolToString()
inviqa/harness-docker pull request #148
Opened 2024-02-22 06:55 UTC by NoDiskInDriveA

Allows passing in optional values like `boolToString(false, 'enable', 'disable')`. Compatible with current one-argument syntax.

2024-02-22 06:57 UTC, kierenevans commented on harness/config/functions.yml
> +    case false: return (string) ($falseVal ?? 'no');
```suggestion
    case true: return (string) ($true_value ?? 'yes');
    case false: return (string) ($false_value ?? 'no');
```

2024-02-22 07:12 UTC, NoDiskInDriveA commented on harness/config/functions.yml
> +    case false: return (string) ($falseVal ?? 'no');
Copy/paste error from my test environment 😬

2024-02-22 07:12 UTC, kierenevans approved these changes

2024-02-22 07:12 UTC, kierenevans commented on harness/config/functions.yml
> +    case false: return (string) ($falseVal ?? 'no');
All good :)

2024-02-22 09:06 UTC, andytson-inviqa requested changes
I don't see the point in this?

```
= @('bool') ? true_value : false_value
```

2024-02-22 15:02 UTC, NoDiskInDriveA commented
@andytson-inviqa I mean...that function already exists hardcoded to `yes` and `no` - the specific use case I had was a project command that I wanted to take `(on|off)` as argument (to keep usage similar) but use different values in the command block without if/else statement.
No saying it has a billion use cases but doesn't hurt either 🤷

2024-02-22 15:20 UTC, andytson-inviqa commented
the yes/no was convention for lots of uses, configuration is needless when it's just as expressive as ternary expression which is more memorable

2024-02-22 16:24 UTC, andytson-inviqa commented
in short we don't really need a ternary function when we have a ternary expression

2024-03-01 10:06 UTC, NoDiskInDriveA commented
@andytson-inviqa I didn't understand at first what you meant, but what you're saying is that instead of an `env` with like `ATTR_VAL: = boolToString(input.command(5) == 'on', 'debug', 'off')` I should use an expression filter in `exec`. Thanks for that tip, I was a bit blind there (mainly because the `@` and `=` still confuse me 🙈 ).

2024-03-01 10:06 UTC, closed without merging

2024-03-01 10:08 UTC, andytson-inviqa commented
in your example
```
   ATTR_VAL: = boolToString(input.command(5) == 'on', 'debug', 'off')
```

```
   ATTR_VAL: "= input.command(5) == 'on' ? 'debug' : 'off'"
```